project_id: '684038'
api_token_env: CROWDIN_PERSONAL_TOKEN
languages_mapping:
  two_letters_code:
    zh-CN: zh-CN
preserve_hierarchy: 1
files:
  - source: /i18n/en/**/*.json
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: []
  - source: /docs/**/*.*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
